server:
  port: 9000

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    customRealm: security
    contextPath: /auth
    adminUser:
      username: admin
      password: password
    customUser:
      username: security-admin
      password: password
    realmImportFile: realm-export.json
