server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9000/auth/realms/security/protocol/openid-connect/token/introspect
          client-id: microservice1
          client-secret: 5FlyzwdNmF68kQFfYzifqAeMmqXOnfoJ

microservice:
  name: Microservice 1

logging:
  level:
    root: INFO
